### ISSUE TITLE
Bookmark Entity 컬럼 종속관계 관련..

### ISSUE THREAD

**Issue by Nam-Ki-Bok** [Nam-Ki-Bok/minutes-of-sentiment-analysis#5]
<img width="529" alt="스크린샷 2021-04-22 오후 5 11 06" src="https://user-images.githubusercontent.com/54533309/115679617-bb1eb480-a38d-11eb-8b9a-5fc2a2e83f58.png">

북마크 테이블 컬럼에 북마크 메모 내용을 저장하는게 있어서 FK 관계가 전부 OneToOne 이어야 하는거 아닌가용..
Entity 만들고 있는데 갑자기 이해가 안가서용..
@9b2n

**Comment by 9b2n** [comment]
한 사람이 여러개의 북마크를 지정할 수 있기때문에 OneToMany인 거 같아요
